openshift-4-compliance/openshift-4-compliance-automation

- open-policy-agent/authentication-user-management/delete-kubeadmin/constraint.yaml
- open-policy-agent/authentication-user-management/delete-kubeadmin/template.yaml
add OPA automation for kubeadmin secret to be deleted.
*NOT TESTES YET!* due to the absence of test env :(
> add deleted kubeadmin rule

- README.md
@igorkchyts Please check that you are able to access the compliance doc reference.
The issue the PR is referenced to is - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/3
> Added a public visible compliance doc reference

- open-policy-agent/trusted-image-sources/disallowedtags/constraint.yaml
change from disallow-latest-tag to disallow-tags
Fixes #13
> modify disallowed tags name 

- open-policy-agent/README.md
Added the [disallow-selfprovisioner](https://github.com/openshift-4-compliance/openshift-4-compliance-automation/tree/master/open-policy-agent/resource-exhaustion/disallow-self-provisioner) and [shorten-tokens](https://github.com/openshift-4-compliance/openshift-4-compliance-automation/tree/master/open-policy-agent/resource-exhaustion/disallow-self-provisioner) to the OPA [README.md](https://github.com/openshift-4-compliance/openshift-4-compliance-automation/blob/master/open-policy-agent/README.md).
> Added policies to the OPA README.md

- README.md
- Delete compliance Operator folder as it is not intended for custom security policies. It should be integrated as solution to comply the cluster with CIS and NIST benchmarks.
> - Delete compliance Operator folder

- kyverno/README.md
- kyverno/networking/httpsonly.yaml
The policy validates that there are no routes with no https configuration.
> Added https only route policy

- kyverno/README.md
- kyverno/authorization/host-namespaces/disallow-host-pid.yaml
Dissallow HostPID access for PODs and custom-scc
> Disallow HostPID access

- redhat-acm/kustomization.yaml
Kustomization deployment strategy implementation.
> Kustomization integration for Advanced Cluster Management policies

- ADR.md
Added the ADR to the repository.
> Added ADR to the repository

- .github/issue_template.md
The template should make opening new issues easier and clearer to understand.
> Template for opening new issues

- redhat-acm/authentication-user-management/gatekeeper-shorten-tokens/gatekeeper-shorten-tokens.yaml
- redhat-acm/authorization/gatekeeper-disalllow-privileged-scc-usage/gatekeeper-disalllow-privileged-scc-usage.yaml
- redhat-acm/authorization/gatekeeper-prevent-default-serviceaccount-usage/gatekeeper-prevent-default-serviceaccount-usage.yaml
- redhat-acm/networking/allow-port-from-namespace-networkpolicy-policy/allow-port-from-namespace-networkpolicy-policy.yaml
- redhat-acm/networking/gatekeeper-allow-httpsonly/gatekeeper-allow-httpsonly.yaml
- redhat-acm/networking/gatekeeper-disallow-external-ip-services/gatekeeper-disallow-external-ip-services.yaml
- redhat-acm/networking/gatekeeper-disallow-nodeport/gatekeeper-disallow-nodeport.yaml
- redhat-acm/resource-exhaustion/gatekeeper-disallow-self-provisioner-policy/gatekeeper-disallow-self-provisioner-policy.yaml
- redhat-acm/resource-exhaustion/limitrange-policy/limitrange-policy.yaml
- redhat-acm/trusted-image-sources/gatekeeper-disallow-image-tags/gatekeeper-disallow-image-tags.yaml
Changing the remediation action in RHACM policies to `inform`.
Reference to issue - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/86
> Change remediationAction to inform in RHACM policies

- redhat-acm/README.md
- redhat-acm/kustomization.yaml
- redhat-acm/resource-exhaustion/resourcequota-policy/resourcequota-policy.yaml
Policy description at - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/95
> Added ResourceQuota policy for RHACM

- open-policy-agent/README.md
- open-policy-agent/authorization/disallow-host-namespaces/constraint.yaml
- open-policy-agent/authorization/disallow-host-namespaces/template.yaml
- open-policy-agent/kustomization.yaml
Issue reference - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/99
> Disallow host namespaces using Gatekeeper

- open-policy-agent/README.md
- open-policy-agent/authorization/disallow-host-network/constraint.yaml
- open-policy-agent/authorization/disallow-host-network/template.yaml
- open-policy-agent/kustomization.yaml
Answers - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/101
> Added disallow-host-network policy for opa

- redhat-acm/README.md
- redhat-acm/authorization/gatekeeper-disallow-host-network/README.md
- redhat-acm/authorization/gatekeeper-disallow-host-network/gatekeeper-disallow-host-network.yaml
- redhat-acm/kustomization.yaml
Fixes https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/105
> Added disallow-host-network policy to RHACM

- redhat-acm/README.md
- redhat-acm/authorization/gatekeeper-disallow-host-namespaces/README.md
- redhat-acm/authorization/gatekeeper-disallow-host-namespaces/gatekeeper-disallow-host-namespaces.yaml
- redhat-acm/kustomization.yaml
Fixes - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/103
> Added hostnamespaces policy to RHACM

- open-policy-agent/README.md
- open-policy-agent/authorization/disallow-cluster-admin/constraint.yaml
- open-policy-agent/authorization/disallow-cluster-admin/template.yaml
- open-policy-agent/kustomization.yaml
Solves https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/108.
> Added disallow-cluster-admin for OPA

- redhat-acm/README.md
- redhat-acm/infrastructure-general/check-fips-compliance-policy/README.md
- redhat-acm/infrastructure-general/check-fips-compliance-policy/check-fips-compliance-policy.yaml
- redhat-acm/kustomization.yaml
Solves - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/126
> Added fips policy

- open-policy-agent/README.md
- open-policy-agent/kustomization.yaml
- open-policy-agent/storage/disallow-emptydir/README.md
- open-policy-agent/storage/disallow-emptydir/constraint.yaml
- open-policy-agent/storage/disallow-emptydir/template.yaml
- open-policy-agent/storage/disallow-emptydir/test/deployment.yaml
Solves issue - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/128.
> Added disallow-emptydir OPA policy

- redhat-acm/README.md
- redhat-acm/kustomization.yaml
- redhat-acm/storage/gatekeeper-disallow-emptydir/README.md
- redhat-acm/storage/gatekeeper-disallow-emptydir/gatekeeper-disallow-emptydir.yaml
Solves https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/130
> Added empty-dir policy for RHACM

- open-policy-agent/README.md
- open-policy-agent/kustomization.yaml
- open-policy-agent/trusted-image-sources/disallowed-registries/README.md
- open-policy-agent/trusted-image-sources/disallowed-registries/constraint.yaml
- open-policy-agent/trusted-image-sources/disallowed-registries/template.yaml
Solves - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/135
> Added disallowed-registries

- redhat-acm/README.md
- redhat-acm/kustomization.yaml
- redhat-acm/trusted-image-sources/gatekeeper-disallowed-registries/README.md
- redhat-acm/trusted-image-sources/gatekeeper-disallowed-registries/gatekeeper-disallowed-registries.yaml
- redhat-acm/trusted-image-sources/gatekeeper-disallowed-registries/kustomization.yaml
Solves - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/137
> Added gatekeeper policy that disallows registries

- deploy/README.md
- deploy/rhacm-policies.yaml
Created a deployment strategy document
> Deployment strategy dox

- redhat-acm/README.md
- redhat-acm/authentication-user-management/shorten-tokens-policy/README.md
- redhat-acm/authentication-user-management/shorten-tokens-policy/shorten-tokens-policy.yaml
- redhat-acm/authentication-user-management/shorten-tokens-policy/shorten-tokens.yaml
- redhat-acm/kustomization.yaml
This is a policy for shortening the access token time to 8 hours.
> added new policy

- kyverno/README.md
- kyverno/kustomization.yaml
- kyverno/trusted-image-sources/replace-image-registry/replace-image-registry.yaml
Solves - https://github.com/openshift-4-compliance/openshift-4-compliance-automation/issues/144
> Added kyverno policy that mutates registry name
